version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
